### ISSUE TITLE
Named playgrounds created without specific directories share packages

### ISSUE THREAD

**Issue by christopher-dG** [rofinn/Playground.jl#61]
```sh
[ ~ ] playground create --name test1
[ info ] Creating playground environment test1...
[ info ] Installing packages from REQUIRE file /Users/degraafc/.playground/REQUIRE...
[ ~ ] playground create --name test2
[ info ] Creating playground environment test2...
[ info ] Installing packages from REQUIRE file /Users/degraafc/.playground/REQUIRE...
[ ~ ] playground activate --name test1
[ ~ ] julia -e 'Pkg.add("JSON")'
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of JSON from https://github.com/JuliaIO/JSON.jl.git
INFO: Installing Compat v0.33.0
INFO: Installing JSON v0.15.1
INFO: Package database updated
[ ~ ]  # Deactivate here
[ ~ ] playground activate --name test2
[ ~ ] julia -e 'println(Pkg.installed())'
Dict("JSON"=>v"0.15.1","Compat"=>v"0.33.0")
```

The reason for this is that playgrounds created without specific directories are symlinked to `~/.playground` instead of being their own directory.

**Comment by rofinn** [comment]
Hmmm, they shouldn't be symlinked to `~/.playground`, but rather `~/.playground/share` by default.

**Comment by rofinn** [comment]
Figured out the reason it was using `~./playground`. The actual bug is that it defaults to using the `default_playground_path: .playground` in `~/.playground/config.yml` when a path isn't specified rather than inferring the path correctly to `~/.playground/share`. They're using the same directory because they're both using `./.playground` from the directory you ran the command from. I should have a fix on master tonight.
